/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import abm.ManejoIp;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelos.Articulo;
import modelos.Proveedor;
import org.javalite.activejdbc.Base;

/**
 *
 * @author nico
 */
public class ArticulosProvee extends javax.swing.JDialog {

    private DefaultTableModel articulosProv; //Tabla Default para tener las opciones de instar y elimnar filas
    private java.util.List<Articulo> listArticulos;
    private ArticuloGui articuloGui;
    private DecimalFormat formateador = new DecimalFormat("############.##");

    /**
     * Creates new form ArticulosProvee
     */
    public ArticulosProvee(java.awt.Frame parent, boolean modal, Proveedor proveedor, ArticuloGui articuloGui) {
        super(parent, modal);
       

        initComponents();
        
        if(proveedor!=null)
            this.setTitle("Artículos que provee "+proveedor.getString("nombre"));
        formateador.getDecimalFormatSymbols().setDecimalSeparator('.');

        articulosProv = (DefaultTableModel) tablaArticulos.getModel(); //convierto la tabla

        this.articuloGui = articuloGui;

        tablaArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArticulosClicked(evt);
            }
        });

        listArticulos = proveedor.getAll(Articulo.class);
        articulosProv.setRowCount(0);
        Iterator<Articulo> it = listArticulos.iterator();
        
        while (it.hasNext()) {
            Articulo art = it.next();
            Object row[] = new String[7];
            row[0] = art.getString("codigo");
            row[1] = art.getString("descripcion");
            row[2] = art.getString("marca");
            row[3]= art.getString("nombre");
            row[4] = art.getBigDecimal("precio_compra").setScale(2, RoundingMode.CEILING).toString();
            row[5]= art.getString("stock_actual");
            row[6]= art.getString("stock_minimo");
            articulosProv.addRow(row);
        }
        
    }

    private void tablaArticulosClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
             Base.openTransaction();
            Articulo articulo = Articulo.findFirst("codigo = ?", tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 0));
            Proveedor papacito = articulo.parent(Proveedor.class);
                        Base.commitTransaction();

            if (papacito == null) {
                articulo.setNombreProv("");
            } else {
                articulo.setNombreProv(papacito.getString("nombre"));
            }

            articuloGui.CargarCampos(articulo);
            articuloGui.setVisible(true);
            articuloGui.toFront();
            this.dispose();
        }
    }



 
    public JTable getTablaArticulosProv() {
        return tablaArticulos;
    }

    public DefaultTableModel getArticulosProv() {
        return articulosProv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Artículos que provee");
        setLocationByPlatform(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artículos que provee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 14))); // NOI18N

        tablaArticulos.setAutoCreateRowSorter(true);
        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripcion", "Marca", "Nombre", "Precio Compra", "Stock", "Stock minimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulos.setToolTipText("Realice doble click sobre el artićulo para ver en detalle");
        tablaArticulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tablaArticulos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaArticulos;
    // End of variables declaration//GEN-END:variables
}
